stages:
  - build
  - test

# Simulation de l'étape de compilation
build_job:
  stage: build
  image: alpine:latest
  script:
    - echo "--- DEBUT DU BUILD ---"
    - echo "Hello World Simulation de la compilation en cours..."
    - sleep 2
    - echo "Build terminé avec succès !"

# Simulation de l'étape de test
test_job:
  stage: test
  image: alpine:latest
  script:
    - echo "--- DEBUT DES TESTS ---"
    - echo "Hello World Execution des tests unitaires..."
    - echo "Succès"
