stages:
  - test
  - build
  - deploy

test:
  stage: test
  image: docker:latest
  script:
    - echo "Running tests..."
    - docker-compose --version

build:
  stage: build
  image: docker:latest
  type: docker-compose-deploy
  script:
    - docker-compose build
  properties:
    compose_file: docker-compose.yml

deploy:
  stage: deploy
  image: docker:latest
  type: docker-compose-deploy
  script:
    - docker-compose up -d
  properties:
    compose_file: docker-compose.yml
    service_name: ""