stages:
  - test
  - build
  - deploy

test:
  stage: test
  image: docker:latest
  script:
    - echo "Running tests..."
    - docker --version

build:
  stage: build
  image: docker:latest
  type: docker-deploy
  script:
    - docker build -t myapp:latest .
  properties:
    image_name: myapp:latest

deploy:
  stage: deploy
  image: docker:latest
  type: docker-deploy
  script:
    - docker run -d --name myapp -p 8080:8080 myapp:latest
  properties:
    image_name: myapp:latest
    container_name: myapp
    port_mapping: "8080:8080"
